namespace: "getstackhead"
name: "module-webserver-nginx"
version: "0.0.0"
authors:
  - "Mario Lubenka <mario.lubenka@googlemail.com>"
dependencies:
  "geerlingguy.nginx": ">=2.8.0,<3.0.0"
tags:
  - demo
  - collection
readme: "README.md"
license: "GPL-2.0"
repository: "https://github.com/getstackhead/module-webserver-nginx"
documentation: "https://github.com/getstackhead/module-webserver-nginx"
#build_ignore:
#  - __tests__
