# This task list sets up Nginx during server setup
---
- name: Deploy additional h5bp Nginx files
  synchronize:
    src: "{{ playbook_dir }}/../vendor/server-configs-nginx/h5bp"
    dest: /etc/nginx
- name: Setup Nginx
  vars:
    nginx_ppa_use: true
    nginx_conf_template: "roles/stackhead_webserver_nginx/templates/nginx/nginx.conf.j2"
    nginx_vhosts: []
    __nginx_user: "stackhead"
    root_group: "stackhead"
  include_role:
    name: geerlingguy.nginx
- name: adjust owner of /var/www directories
  file:
    path: /var/www
    state: directory
    owner: "stackhead"
    group: "stackhead"
    mode: 0755
    recurse: true
- name: adjust owner of /etc/nginx/sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled
    state: directory
    owner: "stackhead"
    group: "stackhead"
    mode: 0755
    recurse: true
- name: Check content after provisioning
  uri:
    url: "http://{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
    return_content: yes
  register: uri_result
  until: '"Welcome to nginx" in uri_result.content'
  retries: 5
  delay: 1
